[project]
name = "social-media-api"
version = "0.1.0"
description = ""
authors = [
    {name = "Yash Saxena",email = "yashsaxena7828@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "django (>=6.0.2,<7.0.0)",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "mysqlclient (>=2.2.8,<3.0.0)",
    "pillow (>=12.1.1,<13.0.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)",
    "python-decouple (>=3.8,<4.0)",
    "drf-spectacular (>=0.29.0,<0.30.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
